# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln ./
COPY Watchlog_Websocket_NET_CORE_8/*.csproj ./Watchlog_Websocket_NET_CORE_8/
RUN dotnet restore

COPY . .
WORKDIR /src/Watchlog_Websocket_NET_CORE_8
RUN dotnet publish -c Release -o /app/publish

# 2. Çalıştırma aşaması
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Watchlog_Websocket_NET_CORE_8.dll"]
